### ISSUE TITLE
Documentation: How to set Perfcounter Permissions 

### ISSUE THREAD

**Issue by ErwinE** [Icinga/icinga-powershell-plugins#119]
Hello,

with the Icinga-Powershell-Plugins we get a lot of Eventlog entries on all Windows systems. 
It´s caused by several checks, which need access to Perfomance Counters. (Diskhealth, UsedPartition, Network, CPU, Memory)
The user which we use for our Icinga Client is "NT Authority/Local Service".

**Example with Check CPU**
Check itself works with no problems:

> PS C:\Windows\system32> Invoke-IcingaCheckCPU -Verbosity 3
> [OK] Check package "CPU Load" (Match All)
> \_ [OK] Core 0: 3.283922%
> \_ [OK] Core 1: 2.993483%
> \_ [OK] Core 2: 3.57436%
> \_ [OK] Core 3: 3.57436%
> \_ [OK] Core Total: 3.35653%
> | 'core_2'=3.57436%;;;0;100 'core_total'=3.35653%;;;0;100 'core_0'=3.283922%;;;0;100 'core_1'=2.993483%;;;0;100 'core_3'=3.57436%;;;0;100
> 0

But after that there are some errors in eventlog:
![image](https://user-images.githubusercontent.com/54027101/102490256-d9d30e80-406e-11eb-84d4-ce15722c38ef.png)

We investigated the exact command which produce these errors:

```
$CounterInstances = New-Object System.Diagnostics.PerformanceCounterCategory("Processor");
$CounterInstances.GetInstanceNames()
2
3
0
1
_Total
```

What we already did:
Put the LocalService user in the "Performance Log Users" group and the "Performance Monitor Users" group.
And we gave some WMI permissions which we found in the documentation, but nothing changed.

In some plugin documentation we saw that permissions for perfomance counters is needed, but we couldn´t find anything which allow us to do this.

Does someone know how to set these permissions? If yes, it would be great to publish this in the documentation.

Thanks & Regards,
Erwin

**Comment by LordHepipud** [comment]
Yes this is an issue we are still investigating. The problem is that the PerfCounter lib will try to access and load all counter categories available on the system. However, users might not have permission to these counters and therefor this error is thrown on the EventLog.

If there is anyone who can point us to the correct direction on how to add proper permissions to these counters, it would be appreciated.
One workaround would be to simply deactivate counters which are affected by this, this will however probably cause weird side effects overall.

**Comment by LordHepipud** [comment]
We updated the IKBW for this: https://github.com/Icinga/icinga-powershell-framework/blob/master/doc/knowledgebase/IWKB000008.md

It seems there is no way to resolve this and should try to get the Inernal REST-Api ready for production.
