### ISSUE TITLE
Invoke-IcingaCheckService - Specific services not working

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icinga-powershell-plugins#129]
Hello,

I tried to monitor following services:
- NTDS
- DHCPServer

Executed with Icinga2 agent / Powershell Framework it results always in this:

```
[UNKNOWN] Check package "Services" (Match All) - [UNKNOWN] DHCPServer: Service not found
\_ [UNKNOWN] DHCPServer: Service not found
```

but if I execute the command direct on Powershell it is just fine:

```
Get-Service > Running  NTDS               Active Directory-Domänendienste
Use-Icinga; Invoke-IcingaCheckService -Service NTDS -Exclude $null -Status Running -Verbosity 3
[OK] Check package "Services" (Match All)
\_ [OK] Service "Active Directory-Domänendienste (NTDS)": Running
| 'pending_paused_services'=0;; 'running_services'=0;; 'pending_continued_services'=0;; 'stopped_services'=0;; 'pending_started_services'=0;; 'service_count'=1;; 'pending_stopped_services'=0;; 'paused_services'=0;; 'service_active_directorydomänendienste_ntd
s'=4;;4 
0
```
```
Get-Service > Running  DHCPServer         DHCP-Server
Use-Icinga; Invoke-IcingaCheckService -Service DHCPServer -Exclude $null -Status Running -Verbosity 3
[OK] Check package "Services" (Match All)
\_ [OK] Service "DHCP-Server (DHCPServer)": Running
| 'service_dhcpserver_dhcpserver'=4;;4 'pending_paused_services'=0;; 'running_services'=0;; 'pending_continued_services'=0;; 'stopped_services'=0;; 'pending_started_services'=0;; 'service_count'=1;; 'pending_stopped_services'=0;; 'paused_services'=0;; 
0
```

ATM I don't see the point where things went south since the command is just copied from debulog of Icinga2 agent.

**Comment by LordHepipud** [comment]
Hello

Thank you for the issue. This problem might simply occur because the user you are running Icinga2/Icinga for Windows with has no read access for this services.
Not all services are exposed for all users and might require higher privileges to access them.

Thats why your local PowerShell is listing the service, while the Icinga Agent itself doesn't. We are already investigating similar issues on another project and are internally discussing on how we want to move forward regarding permission handling to provide a secure environment but are still able to execute checks and fetching all required information.

**Comment by m4k5ym** [comment]
Noted. Thanks for the very quick response.

Is there a guide available to solve this issue in "powershell-framework best practise way" or do I have to figure a way myself?

**Comment by LordHepipud** [comment]
Right now there is no proper solution available. I have one here, but I'm not sure about possible side effects. Because you could grant read-access to services to certain users, I'm however not sure if this will not cause problems on different ways.

For this you simply have to compile and apply a security catalog.

As we had a similar issue on the cluster plugins, I shared a solution I figured out: https://github.com/Icinga/icinga-powershell-cluster/issues/17#issuecomment-730721759

However, please be careful with this as mentioned earlier I have no idea about possible side effects.

**Comment by m4k5ym** [comment]
What side effects you might expect in the first place?

I will hook up my test bench tomorrow with a few windows server and try the "workaround"

Maybe we will find out if it would brake something or just works.

**Comment by KreativeKrise** [comment]
I have the exactly same problem.

But on one of my domain controllers the icinga agent can read NTDS. The icinga2 service is running as LocalSystem on both domain controllers.

I also tried to run a powershell session as LocalSystem via `psexec.exe -i -s powershell.exe` (https://docs.microsoft.com/de-de/sysinternals/downloads/psexec). There I can run the `Invoke-IcingaCheckService`-commands without any problem. So in theory the account LocalSystem should have the rights to read the service status.

**Comment by LordHepipud** [comment]
If the service itself is running with `LocalSystem` permissions this shouldn't be a problem. So on both systems you are running the Icinga Agent as `LocalSystem` and only on one the monitoring is working as expected? With the same version of the PowerShell plugins?

**Comment by KreativeKrise** [comment]
Yes, both systems are running the Icinga Agent as `LocalSystem` and use the version 1.3.1 of PowerShell plugins.

On system 1 the service `NTDS` was found by the Icinga Agent, but `DHCPserver` was not.
On system 2 both services were not found by the Icinga Agent.

**Comment by LordHepipud** [comment]
Are they configured differently? Both systems should delivery the same result with the identical plugin versions.
Therefor I don't get why they work differently. For the access there might be other restrictions in place that even `LocalSystem` can't access them. We will try to work a way around that.

**Comment by KreativeKrise** [comment]
The only difference is, that the system, which finds `NTDS`, has "Microsoft Azure AD Connect" installed. The rest should be identical.

**Comment by m4k5ym** [comment]
I'm out. Good luck!

**Comment by LordHepipud** [comment]
To resolve this, I would advise using [JEA Profiles](https://icinga.com/docs/icinga-for-windows/latest/doc/130-JEA/01-JEA-Profiles/)

We introduced the support with v1.6.0 and resolves all of the current permissions problems for services, tasks and other related topics.
