### ISSUE TITLE
Invoke-IcingaCheckUpdates returns always 0 to Icinga

### ISSUE THREAD

**Issue by tsteuerer** [Icinga/icinga-powershell-plugins#239]
No matter what I try, Invoke-IcingaCheckUpdates alway returns 0 pending updates to Icinga
![SP_13_20_36_000066](https://user-images.githubusercontent.com/88784601/140059193-1f90f3e3-26b3-48df-b1e8-cf7646b5b6af.png)
.
When I do the check directly on the Host, it returns correct values and warning levels.
```
PS C:\Windows\system32> Invoke-IcingaCheckUpdates -Warning 3 -Critical 5
[WARNING] Windows Updates [WARNING] Pending Update Count
\_ [WARNING] Pending Update Count
   \_ [WARNING] Pending Update Count: 5 is greater than threshold 3
| 'pending_update_count'=5;3;5
1
```
Due to Issue [https://github.com/Icinga/icinga-powershell-plugins/issues/184] I thought there could be something wrong with my Command definition in Icinga, so I re-exported a Director Basket and imported it in Icinga without any success.

**Comment by LordHepipud** [comment]
I don't think the issue is the command itself. I assume this is a simple permission issue. We are using COM Objects to fetch the Windows Update query. If the user you are using is not able to fetch the updates or no updates are returned, this could be a problem.

Based on my research, it is not possible to modify the permissions of a user to make this check work. One solution could be, to test using the [Icinga for Windows JEA Profile](https://icinga.com/docs/icinga-for-windows/latest/doc/130-JEA/01-JEA-Profiles/)

This should ensure that the check has all permissions to fetch required updates.

**Comment by tsteuerer** [comment]
Indeed, it is a permission Issue. The Icinga Client runs by default as Network Service. When I change it to run as LocalSystem (not NT Authority\System; this also doesn't work), I'll get the correct check results.
The service user can be changed by executing
`Set-IcingaAgentServiceUser -User 'LocalSystem' -SetPermission;`
though having the Agent running as LocalSystem seems to be not very secure. So I'll maybe give the JEA profiles a try later on.
