### ISSUE TITLE
JEA Error in Get-IcingaPartitionSpace.psm1

### ISSUE THREAD

**Issue by bargru** [Icinga/icinga-powershell-plugins#270]
When executing `Install-IcingaSecurity` I get the flowing error message:

``` [Error]: Unable to include module "icinga-powershell-plugins" into JEA profile. The file "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Get-IcingaPartitionSpace.psm1" is using one or more [ScriptBlock] variables which are forbidden in JEA context. ```
I'm using the icinga-powershell-plugins version 1.7.0

Is this a bug or a not avoidable thing?

Edit: result from `Get-IcingaJEAConfiguration`

```PS C:\Windows\system32> Get-IcingaJEAConfiguration
[Warning]: The module "icinga-powershell-plugins" is using "Add-Type" definitions for file "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Get-IcingaDiskAttributes.psm1". Ensure you validate the code before trusting this publisher.
[Error]: Unable to include module "icinga-powershell-plugins" into JEA profile. The file "C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Get-IcingaPartitionSpace.psm1" is using one or more [ScriptBlock] variables which are forbidden in JEA context.```

**Comment by LordHepipud** [comment]
Hello,

thank you for the issue. This will be fixed with v1.8.0: #271

You can right now use

```powershell
Install-IcingaSecurity -AllowScriptBlocks
```

to include it anyway

**Comment by bargru** [comment]
Ok, using `-AllowScriptBlocks` works. 

Now I'm just getting a `|` as plug-in output in Icinga Web with an OK status. I also do not understand where I must set the `-JEAProfile` argument. 

I see that the next release will fix some bugs related to JEA. I might run in to one of them. Or the documentation isn't clear enough?

**Comment by LordHepipud** [comment]
I assume you are running into this: https://github.com/Icinga/icinga-powershell-framework/pull/407

We removed that because it was not needed at all, but in JEA context this causes the mentioned result.
You don't have to set `-JEAProfile` or anything, because Icinga for Windows and the plugin configuration will deal with creating a proper JEA shell.

The entire handling is done within `Exit-IcingaExecutePlugin`. We wanted to introduce these methods slowly, do not overwhelm everyone with plenty of configuration steps.

**Comment by bargru** [comment]
Thank you for the help! Now everything works as desired.

The JEA Support is awesome! No need to set local system permissions :)
