### ISSUE TITLE
Invoke-IcingaCheckUsedPartitionSpace: Set lower threshold MB of space

### ISSUE THREAD

**Issue by pakyg** [Icinga/icinga-powershell-plugins#304]
Hi, I can't correctly set the thresholds for checking on local disks. I would need to have a critical when the free space on the disk is less than 500MB. I cannot put the value in %, as I have many discs with different capacities.
I ask you, is there the possibility to insert a free space threshold of less than 500MB?

Thanks,
Greetings

**Comment by LordHepipud** [comment]
Hello,

which version of the plugin are you using? The new versions by default allow to check for the free space. To check if less than 500 MiB are available:

```powershell
Invoke-IcingaCheckPartitionSpace -Critical '500MiB:'
```

or for MB (preferred is MiB, because this is the value displayed by the Windows Explorer)

```powershell
Invoke-IcingaCheckPartitionSpace -Critical '500MB:'
```

Important is the `:` at the end, which changes the handling from `value > threshold` to `value < threshold`.

There are also docs for this: https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/

**Comment by pakyg** [comment]
It works perfectly, thanks!
Greetings
