### ISSUE TITLE
Autoremediation Windows Services - Output Problem

### ISSUE THREAD

**Issue by pakyg** [Icinga/icinga-powershell-plugins#311]
Hello,
I have a problem running the event command on the Windows services check.

As you can see from the debug.log, when I try to run the script, it fails due to a special character present in the plugin output.

Debug Log:
![image](https://user-images.githubusercontent.com/70367256/181788551-df5c038d-d674-4f57-94e9-ca93c38df5e2.png)

I use "Invoke-IcingaCheckService" and in the output, when reporting a critical service, insert the special character "\ _" .. Is there a way to modify the output and not insert special characters?

I am attaching the event command script as an example:
![image](https://user-images.githubusercontent.com/70367256/181787732-0e48b468-cc81-4cbc-a925-e578eca63ae1.png)

In addition, I am also attaching the configuration of the event command on the Icinga side:
![image](https://user-images.githubusercontent.com/70367256/181787903-3e42606f-4148-4f06-93ec-65bfecd58ba1.png)

![image](https://user-images.githubusercontent.com/70367256/181787956-d2c6c4fd-027d-42e6-b92d-cde3f205abb6.png)

Is there a way to change the output and not use special characters like "\"?

Thank you
Greetings

**Comment by LordHepipud** [comment]
Thank you for the report. There is no way to remove any special characters or cleanout the output from those.
If the string is properly formatted as string, the PowerShell should take care of that and preventing from this to happen.

Within Icinga you will have the string values into `'` single quotes, to ensure they are defined as a plain string. Otherwise you will run into the problems you encounter for the moment.

The easiest way would to be to update your command arguments and wrap you `$service.output$` into `'`, like this:

```
'$service.output$'
```

There is also a KB entry for this, those the problem in this case is a little different:

https://icinga.com/docs/icinga-for-windows/latest/doc/knowledgebase/IWKB000002/

I hope this helps!

**Comment by pakyg** [comment]
Problem solved
Thank you :)
