### ISSUE TITLE
Invoke-IcingaCheckTimeSync - Time Offset Problems

### ISSUE THREAD

**Issue by Lenerd88** [Icinga/icinga-powershell-plugins#331]
Hey Guys,

I currently working on a monitoring for the timecheck and have the problem that the time offset is constantly running on warning. The check should send a warning or critical at 15s.

Check:

Invoke-IcingaCheckTimeSync -Server '$ARG1$' -TimeOffset 10ms -Warning '15s' -Critical '15s' -Verbosity 2"

Result:

[CRITICAL] Time Package [CRITICAL] Time Offset (-10ms)
\_ [OK] Sync Status: NoLeapWarning
\_ [CRITICAL] Time Offset: -10ms is greater than threshold 15s
\_ [OK] Time Service: Running

I have a mistake in thinking somewhere, could you help me with that?

Thanks alot!

**Comment by LordHepipud** [comment]
Hello,

thank you for your message. The problem is, that the result for the time offset is a negative value. By default in the way you are writing the threshold, the plugin will consider any value below 0 and above your input as warning/critical

https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/

```powershell
Invoke-IcingaCheckTimeSync -Server '$ARG1$' -TimeOffset 10ms -Warning '~:15s' -Critical '~:15s' -Verbosity 2
```

This will ensure that only positive values are considered and the plugin will throw an error if the time offset is above 15s
