### ISSUE TITLE
CPU top process list causing timeouts

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga-powershell-plugins#418]
Dear Mr. @LordHepipud, I am reaching out regarding bugs you've been introducing 😉 

It appears to be that the "Top 10 Process CPU usage" feature in Invoke-IcingaCheckCPU can cause timeouts.

We are still using the powershell-connector and just upgraded to 1.12.3.

    UNKNOWN - timeout during HTTP request: Post "https://localhost:5668/v1/checker?command=Invoke-IcingaCheckCPU": context deadline exceeded (*fmt.wrapError)

Some systems have this error occasionally for a few check executions, then the timeout is no longer breached. On a particular system I have the error permanently, so I've added `-DisableProcessList` there and the timeout went away:

![image](https://github.com/user-attachments/assets/a749dfbb-e06e-4fdc-8b89-ee1e1c191dcd)

Anything you've want me to test or debug? Gimme a call if you want!

**Comment by lazyfrosch** [comment]
Another system where it is flapping every few checks.

We've decided to disable the feature for now...

![image](https://github.com/user-attachments/assets/36073111-5da3-478e-ad1f-e9c3ced44d52)

**Comment by LordHepipud** [comment]
Thank you for the issue! Yes, this feature can cause performance and timeout issues which I learned recently.
Please use the flag `-DisableProcessList` for the plugin, which resolves this issue as you mentioned.

This feature will be re-designed in future Icinga for Windows versions, because right now it causes way too much issues.
