### ISSUE TITLE
The eventLog Monitoring is very CPU intensive.

### ISSUE THREAD

**Issue by bobapple** [Icinga/icinga-powershell-plugins#70]
The eventLog Monitoring is very CPU intensive.
When multiple eventIDs are monitored in multiple single service on the same server the CPU struggles a lot. 
I have tested 47 EventID in 47 Single Service and it really thrashes the CPU badly. 
The reason behind creating 47 single service is because when 2 event ID fires together at the same sampling interval customer need 2 tickets instead of 1. 
Some documents related to improvement of performance in log monitoring
https://devblogs.microsoft.com/scripting/how-to-improve-the-performance-of-a-powershell-event-log-query/
https://www.reddit.com/r/PowerShell/comments/69kbkd/getwinevent_vs_geteventlog_performance/
https://stackoverflow.com/questions/60601715/event-log-query-with-get-winevent-get-eventlog-is-very-slow-when-querying-shut

This also suggest that having Provider as filter parameter is better than having Log Name mentioned as Filter

_Originally posted by @radioactive9 in https://github.com/Icinga/icinga-powershell-plugins/issues/66#issuecomment-689264833_

**Comment by bobapple** [comment]
REF/IC/27529

**Comment by LordHepipud** [comment]
Hello @radioactive9

Thank you for your report. Would it be possible to share two configurations of your eventlog check? I agree that eventlog is a heavy task, for that reason the Framework and this plugin specifically are working with a cache.

If for example you are running the plugin with this argument two times in a row:

```powershell
Invoke-IcingaCheckEventlog -LogName Application -IncludeEventId 15;
```

the result and query will change. On the first run, the entire eventlog is scanned and the entire output is filtered which is heavily CPU intensive.
On the second call how ever the plugin will use a cached time index and add it to the filter. This means on the second call only the events written since the last plugin execution call are processed. If only 5 events occured since then, only these events will be returned.

For me it would be important to understand if the problem is the EventLog plugin itself or propably the Framework, taking too much resources while loading.

In addition I will play around a little more with the provided sugestion - thanks a lot!

**Comment by radioactive9** [comment]
Hello Christian

Thanks for taking this up. I have 47 single service checks which looks like below with different EventIDs.

```
apply Service "XXX-P_MS_P_EvtLogID1101" {
    import "XXX-tmplService-MS-PS_EventLog"


    assign where "XXX-tmplHost-MS" in host.templates
    vars.IcingaCheckEventlog_Array_IncludeEventId = [ "1101" ]
    vars.IcingaCheckEventlog_Object_Warning = "~:0"
    vars.IcingaCheckEventlog_String_LogName = "Application"
    vars.IcingaCheckEventlog_Switchparameter_DisableTimeCache = false

    import DirectorOverrideTemplate
}

Clearly lot of powershell process is spinning up and soon the CPU is spiking to 100 %

More-over the method of Get-EventLog method used is way slower than Get-WinEvent

![image](https://user-images.githubusercontent.com/30764851/92589705-94a58080-f2b8-11ea-9747-41bc149021bb.png)

```

**Comment by LordHepipud** [comment]
I have created a PR to improve the plugin alot and to ensure the output is more accurated.

Changes made:
* Plugin will by default only go back 2 hours on first run or by using `-DisableTimeCache` (improves Performance a lot)
* Added log message to output on different check element on Verbosity 1
* Added filter for eventlog source
* Filtering for EventID's is now working properly by using the EventId instead of the InstanceId
* Changed grouping of events by Source instead of message (reduces output)

Waiting for tests and feedback for this now.

**Comment by K0nne** [comment]
I have tested the PR and found no issues so far. 
The filtering for EventIDs is working properly now 👍
