### ISSUE TITLE
IcingaCheckService for all Autostart Services shows 0 services and exit with OK

### ISSUE THREAD

**Issue by MartinBuuhh** [Icinga/icinga-powershell-plugins#78]
Hi, we newly started to use the IcingaCheckService (icinga-powershell-plugins-1.2.0) with the icinga2-powershell-framework 1.2.0 .

For a reason i dont understand, the service check behaves different from what i expect.

-> if we just execute the plugin, without any arguments, it throws OK with 0 Services found.

**see here:**
PS C:\> Use-Icinga; Invoke-IcingaCheckService
[OK] Check package "Services"
| 'pending_paused_services'=0;; 'running_services'=0;; 'pending_continued_services'=0;; 'stopped_services'=0;; 'pending_started_services'=0;; 'service_count'=0;; 'pending_stopped_services'=0;; 'paused_services'=0;;
0

-> when i just try it manually to find services, that are marked for autostart powershell outputs different things

**see here:**
PS C:\> Get-WmiObject -Class Win32_Service | Select-Object Name,State,StartMode | Where-Object {$_.State -ne "Running" -and $_.StartMode -eq "Auto"}

Name           State   StartMode
----           -----   ---------
RemoteRegistry Stopped Auto
sppsvc         Stopped Auto

So there are at least 2 Services in autostart but they are stopped.

furthermore i expect the the framework service plugin to output the count of services in autostart as perfdata too.
What im doing wrong?

Every other framework Plugin like CPU and so on is working fine. Only that check Service is doing strange things.

If i use the service plugin with arguments for special services, it works fine.

In the Icinga2 Documentation it says " If no specific services are configured to check for, the plugin will lookup all services which are configured to run automatically on the Windows startup and report an error in case the service is not running and was not terminated properly. More Information on https://github.com/Icinga/icinga-powershell-plugins"

So i expected it to work without arbuments too

**Comment by LordHepipud** [comment]
Hello and thank you for the issue. In general the plugin is doing exactly on what is described.

Only because a Windows services is set to run automatically does not mean it has to be actually running. For example we can have a look on the Microsoft Edge Update service. This service is configured to start automatically with the Windows system start, is how ever exiting itself once completed.

By executing the plugin as mentioned, we will not see an error:

```powershell
icinga { Invoke-IcingaCheckService }

[OK] Check package "Services"
| 'pending_paused_services'=0;; 'running_services'=0;; 'pending_continued_services'=0;; 'stopped_services'=0;; 'pending_started_services'=0;; 'service_count'=0;; 'pending_stopped_services'=0;; 'paused_services'=0;;
```

If we how ever check directly for the `edgeupdate` service, the result is different - as expected:

```powershell
icinga { Invoke-IcingaCheckService -Service 'edgeupdate' }

[CRITICAL] Check package "Services" - [CRITICAL] Service " Microsoft Edge-Update-Dienst (edgeupdate) (edgeupdate)"
\_ [CRITICAL] Service " Microsoft Edge-Update-Dienst (edgeupdate) (edgeupdate)": Value "Stopped" is not matching threshold "Running"
| 'pending_paused_services'=0;; 'running_services'=0;; 'pending_continued_services'=0;; 'stopped_services'=1;; 'pending_started_services'=0;; 'service_count'=1;; 'pending_stopped_services'=0;; 'paused_services'=0;; 'service_microsoft_edgeupdatedienst_edgeupdate_edgeupdate'=1;;4
```

A valid example that the plugin is working would be on my local machine, where the `Origin Web Helper Service` for the Origin Game Launcher is configured automatically, but failing with an error during start:

```powershell
icinga { Invoke-IcingaCheckService }

[CRITICAL] Check package "Services" - [CRITICAL] Service "Origin Web Helper Service (Origin Web Helper Service)"
\_ [CRITICAL] Service "Origin Web Helper Service (Origin Web Helper Service)": Value "Stopped" is not matching threshold "Running"
| 'service_origin_web_helper_service_origin_web_helper_service'=1;;4 'pending_paused_services'=0;; 'running_services'=0;; 'pending_continued_services'=0;; 'stopped_services'=1;; 'pending_started_services'=0;; 'service_count'=1;; 'pending_stopped_services'=0;; 'paused_services'=0;;
```

We can validate this by using the Icinga Service command to dig a little deeper:

```powershell
icinga { (Get-IcingaServices).'Origin Web Helper Service'.configuration }

Name                           Value
----                           -----
CanPauseAndContinue            False
CanStop                        False
ServiceUser                    NT AUTHORITY\LocalService
ServiceType                    {value, raw}
StartType                      {value, raw}
CanShutdown                    False
ServiceHandle
Status                         {value, raw}
ExitCode                       1077
```

As we see, the ExitCode is 1077 which means the service exit itself with an error, which is capurted by the plugin.

It is true that for example the mentioned services `RemoteRegistry` and `sppsvc ` are not running while set to start automatically, but this might be the intended behaviour of the service to do one task during startup and exit itself once done.

Does this make it more clear on how the plugin is working?

**Comment by LordHepipud** [comment]
I just created a PR to improve the output for the automatic service check. Could you please have a look on it and test the new version?

Thank you in advance!

**Comment by LordHepipud** [comment]
Hello,

did you have the time to check the PR and review it?

**Comment by LordHepipud** [comment]
Hello,

do you have feedback for us on the new plugin version which is listed on the PR?
I will merge the PR into the master next week if no additional feedback is send.
