### ISSUE TITLE
Invoke-IcingaCheckScheduledTask returns false perfdata

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icinga-powershell-plugins#97]
Invoke-IcingaCheckScheduledTask returns invalid perfdata. Either remove them at all (state check) or print out correct perfdata which can be used by icinga. Or disable them by default.

Why i dont disable it and be quiet. Most of the user will not disable them and then they will get a lot of warning entries in the icinga.log about broken perfdata from this check.

For perfdata see this [guideline](https://nagios-plugins.org/doc/guidelines.html#AEN200)

```
PS C:\Users\Administrator> Invoke-IcingaCheckScheduledTask -TaskName 'QueueReporting' -State 'Ready';
[OK] Check package "Scheduled Tasks"
| 'queuereporting_microsoftwindowswindows_error_reporting'=Ready;;Ready
```

**Comment by Mikesch-mp** [comment]
Also the output 
```
Value "Ready" is not matching threshold "Disabled"
```

should be more hnting the asked state it should have like
```
Value "Ready" is not matching state "Disabled"
```

and if you are at it, i think making the State parameter an array would be nice. So we dont get an critical when the tasks runs ;)

**Comment by LordHepipud** [comment]
Thank you very much - I just created a PR to fix the invalid performance metrics of the plugin. That sadly slipped through.

Renaming the check output `Value "Ready" is not matching threshold "Disabled"` is not yet possible with the Framework, as this is a generic approach.

For converting the argument to an array I agree that the current implementation did not consider this. How ever, there is a mayjor problem for this because as far as I can tell we would not be able to create generic arrays within the Icinga Director for example (will have to re-evaluate).

I would want to have a list of fixed items (in this case the states) I can add into an array instead of having to Copy&Paste them from the help description.

This will require a more detailed lookup.

**Comment by Mikesch-mp** [comment]
Same Problem with Invoke-IcingaCheckFirewall, True is not a correct perfdata :)

**Comment by LordHepipud** [comment]
I created a linked PR for the states of the plugin. This will change them from string to array, allowing to set multiple values.

How ever: You will require to update the Framework as well to render a proper configuration, as arrays with a ValidateSet were not supported before. In addition, you will have to update your configuration once importing the Director basket and re-assign your values.

I hope this is also clear by having a look on the [upgrading docs](https://github.com/Icinga/icinga-powershell-plugins/blob/feature/invoke_icingacheckscheduledtask_multi_states/doc/30-Upgrading-Plugins.md#plugin-argument-changes-breaking-changes)

Once I received feedback I will merge the PR.

**Comment by Mikesch-mp** [comment]
I will test it these days and give feedback

**Comment by LordHepipud** [comment]
Hello,

did you have the opportunity to check the plugin yet?

**Comment by LordHepipud** [comment]
I did som tests and from my side it looks fine. I will merge it if no negative feedback is added by Monday.
In case the upgrading docs are followed, there should be no issue in this PR, otherwise the plugin will throw exceptions.
